Q1. Create a NumPy 1D Array and Perform Basic Operations

In [1]:
import numpy as np


arr = np.array([10, 20, 30, 40, 50])

print("Original Array:", arr)


print("After Adding 2:", arr + 2)


print("After Multiplying by 3:", arr * 3)


print("After Dividing by 2:", arr / 2)

Original Array: [10 20 30 40 50]
After Adding 2: [12 22 32 42 52]
After Multiplying by 3: [ 30  60  90 120 150]
After Dividing by 2: [ 5. 10. 15. 20. 25.]


Q2(a). Reverse the NumPy Array

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

print("Original Array:", arr)


reverse_arr = arr[::-1]

print("Reversed Array:", reverse_arr)

Original Array: [1 2 3 6 4 5]
Reversed Array: [5 4 6 3 2 1]


Q2(b)(i). Find Most Frequent Value and Indices

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])


values, counts = np.unique(arr, return_counts=True)


most_freq = values[np.argmax(counts)]


indices = np.where(arr == most_freq)[0]

print("Most Frequent Value:", most_freq)
print("Indices:", indices)

Most Frequent Value: 1
Indices: [0 5 7 8 9]


Q2(b)(ii). Find Most Frequent Value and Indices

In [4]:
import numpy as np

arr = np.array([1,1,1,2,3,4,2,4,3,3,3])

values, counts = np.unique(arr, return_counts=True)

most_freq = values[np.argmax(counts)]

indices = np.where(arr == most_freq)[0]

print("Most Frequent Value:", most_freq)
print("Indices:", indices)

Most Frequent Value: 3
Indices: [ 4  8  9 10]


Q3. Access Elements from a 2D Array

In [5]:
import numpy as np

arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

print("Array:")
print(arr)


print("1st Row, 2nd Column:", arr[0,1])


print("3rd Row, 1st Column:", arr[2,0])

Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
1st Row, 2nd Column: 20
3rd Row, 1st Column: 70


Q4. Create a 1D Array Using linspace()

In [6]:
import numpy as np


Yashit_Arora = np.linspace(10, 100, 25)

print("Array:")
print(Yashit_Arora)


print("Shape:", Yashit_Arora.shape)


print("Dimensions:", Yashit_Arora.ndim)


print("Total Elements:", Yashit_Arora.size)


print("Data Type:", Yashit_Arora.dtype)


print("Bytes Consumed:", Yashit_Arora.nbytes)


print("Transpose using transpose():")
print(Yashit_Arora.transpose())


print("Transpose using T:")
print(Yashit_Arora.T)

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape: (25,)
Dimensions: 1
Total Elements: 25
Data Type: float64
Bytes Consumed: 200
Transpose using transpose():
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2D Array and Perform Operations

In [7]:
import numpy as np

# Create 3x4 array
ucs420_yashit_arora = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,15,20,35]
])

print("Original Array:")
print(ucs420_yashit_arora)


print("Mean:", np.mean(ucs420_yashit_arora))


print("Median:", np.median(ucs420_yashit_arora))


print("Maximum:", np.max(ucs420_yashit_arora))


print("Minimum:", np.min(ucs420_yashit_arora))


print("Shape:", ucs420_yashit_arora.shape)


reshaped_ucs420_yashit_arora = ucs420_yashit_arora.reshape(4,3)

print("\nReshaped Array (4x3):")
print(reshaped_ucs420_yashit_arora)


resized_ucs420_yashit_arora = np.resize(ucs420_yashit_arora, (2,6))

print("\nResized Array (2x6):")
print(resized_ucs420_yashit_arora)

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Shape: (3, 4)

Reshaped Array (4x3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2x6):
[[10 20 30 40 50 60]
 [70 80 90 15 20 35]]
